repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ['--check']
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - "-q"
          - "3"
          - "-I"
          - ".codespell-ignore.txt"
          - "README.md"
          - "docs"
