repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ['--check']
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - "-q"
          - "3"
          - "-I"
          - ".codespell-ignore.txt"
          - "README.md"
          - "docs"
  - repo: local
    hooks:
      - id: version-sync
        name: Version sync check
        entry: .pre-commit-hooks/version-sync.sh
        language: script
        pass_filenames: false
        stages: [commit]
